
# ==============================
#  Awesome-Lazy-Zsh Configuration
#  Generated by Awesome-Lazy-Zsh
#  https://github.com/AmJaradat01/awesome-lazy-zsh
# ==============================

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git git-flow fzf z zsh-autocomplete zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# eval "$(starship init zsh)"

# Homebrew PATH for Apple Silicon
export PATH="/opt/homebrew/bin:$PATH"

# Git Branch Function
git_branch() {
    git branch 2>/dev/null | grep '^*' | colrm 1 2
}

# System Optimizations
# macOS specific settings
export BROWSER="open"
eval "$(/opt/homebrew/bin/brew shellenv)"

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh

# Added by tec agent
[[ -x /Users/carloscorvaia/.local/state/tec/profiles/base/current/global/init ]] && eval "$(/Users/carloscorvaia/.local/state/tec/profiles/base/current/global/init zsh)"

# fix-release-from-main script for admin-web conveyor releases
alias fix-release-from-main="$HOME/fix-release-from-main"

# Admin Web commits script alias
alias awc="$HOME/scripts/get-admin-web-commits-json.sh"

# pnpm
export PNPM_HOME="/Users/carloscorvaia/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
